from .tacdexhand_gelsighthand import (
    TACDEXHAND_5FINGERS_GELSIGHTHAND_RIGID_CFG,
    TACDEXHAND_GELSIGHTHAND_RIGID_CFG,
)

__all__ = ["TACDEXHAND_GELSIGHTHAND_RIGID_CFG", "TACDEXHAND_5FINGERS_GELSIGHTHAND_RIGID_CFG"]

